USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY "MYSQL_ROOT_PASSWORD";
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO "WP_USER"@'%' IDENTIFIED BY "WP_PASSWORD";
DROP DATABASE test;
FLUSH PRIVILEGES;
