USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON . TO 'root'@'%' IDENTIFIED BY "$MYSQL_ROOT_PASSWORD";
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO "$WORDPRESS_DB_HOST"@'%' IDENTIFIED BY "$WORDPRESS_DB_PASSWORD";
FLUSH PRIVILEGES;
