apiVersion: v1  
  
kind: Secret  
metadata:  
  name: influxdb-secrets  
type: Opaque  
stringData:  
  INFLUXDB_ADMIN_USER: admin  
  INFLUXDB_ADMIN_PASSWORD: kraken  
  INFLUXDB_DB: admin
  INFLUXDB_USER: user  
  INFLUXDB_USER_PASSWORD: kraken
---
apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: kraken
