USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY "MYSQL_ROOT_PASSWORD";
CREATE DATABASE IF NOT EXISTS wordpress;
-- GRANT ALL PRIVILEGES ON wordpress.* TO "WP_USER"@'%' IDENTIFIED BY "WP_PASSWORD";
DROP DATABASE IF EXISTS test;
FLUSH PRIVILEGES;
