apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  ports:
    - port: 21
      name: ftp
  selector:
    app: ftps
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps:agossuin
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
