apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.64.12
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
      - image: phpmyadmin:agossuin
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000
