apiVersion: v1  
  
kind: Secret  
metadata:  
  name: influxdb-secrets  
type: Opaque  
stringData:  
  INFLUXDB_ADMIN_USER: admin  
  INFLUXDB_ADMIN_PASSWORD: kraken  
  INFLUXDB_DB: admin
  INFLUXDB_USER: user  
  INFLUXDB_USER_PASSWORD: kraken
---
apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: kraken
---
apiVersion: v1

kind: Secret
metadata:
  name: nginx-secrets
type: Opaque
stringData:
  SSH_USER: james
  SSH_PASSWORD: bond
---
apiVersion: v1

kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:  
  MYSQL_ROOT_PASSWORD: password
---
apiVersion: v1

kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
stringData:  
  WP_USER: john
  WP_PASSWORD: snow
  