kind: Service
apiVersion: v1
metadata:
  name: wordpress
spec:
  ports:
    - port: 5050
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.99.131
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:agossuin
        imagePullPolicy: Never
        name: wordpress
      restartPolicy: Always
