FROM alpine:latest

ARG FTP_USER=user
ARG FTP_PASSWORD=password

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk update && apk add openssl pure-ftpd@testing telegraf@testing

RUN adduser -D -g '' -h /ftps/$FTP_USER $FTP_USER;\
    echo "$FTP_USER:$FTP_PASSWORD" | chpasswd

COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

RUN mkdir -p /ftps/$FTP_USER && chown -R $FTP_USER:$FTP_USER /ftps/$FTP_USER

RUN openssl req -x509 -nodes -days 7300 -newkey rsa:2048 -subj "/CN=BE/O=$FTP_USER" -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem

RUN chmod 600 /etc/ssl/private/pure-ftpd.pem

EXPOSE 21 30020 30023

CMD nohup sh -c "(telegraf;pkill pure-ftpd)&"; /usr/sbin/pure-ftpd -j -Y 2 -p 30020:30023 -P "$ftps"
