USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY "PASSWORD";
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO "wp-user"@'%' IDENTIFIED BY "PASSWORD";
DROP DATABASE test;
FLUSH PRIVILEGES;
