{
 "title": "InfluxDB Internal Basics",
 "description": "InfluxDB Bare Bones Basics internal data explorer.\r\n\r\n + Lists Databases\r\n + Lists Measurements\r\n + Lists Retention policies\r\n + Lists Series\r\n + Lists Field Keys\r\n + Lists Tag Keys\r\n + Lists Tag Values\r\n",
 "tags": [
  "influxdb",
  "internal",
  "metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   { "name": "database", "label": "Database", "query": "show databases" },
   {
    "name": "tag_key",
    "label": "Tag Key",
    "query": "SHOW TAG KEYS ON \"$database\""
   }
  ]
 },
 "panels": [
  {
   "title": "Databases",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW DATABASES",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measurements",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW MEASUREMENTS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Field Keys",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW FIELD KEYS ON \"$database\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tag Keys",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG KEYS ON \"$database\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tag Values",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES ON \"$database\" WITH KEY = \"$tag_key\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retention policies",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW RETENTION POLICIES",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Series",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW SERIES",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}